(function(){'use strict';function p(){var a=q;0===(a.a&8)&&(a.a|=8,window.requestAnimationFrame(a.i));return a.f}function r(a){this.b=new window.MutationObserver(a);this.a=document.createTextNode("");this.b.observe(this.a,{characterData:!0})}function t(a){var b="__pms"+Math.random().toString();window.addEventListener("message",function(d){d.source===window&&d.data===b&&a()})}function u(){this.a=0;this.b=[];this.g=this.f=this.c=null}
function y(a,b,d){var c;void 0===d&&(d=-1);if(-1===d)a.a|=2,null===a.c&&(a.c=[]),a.c.push(b);else{for(a.a|=1;d>=a.b.length;)a.b.push(null);c=a.b[d];null===c&&(c=a.b[d]=[]);c.push(b)}}var q=null;function z(){this.c=q.b;this.b=this.a=null}function A(a,b){this.a=a;this.b=b}function B(a,b){var d=a.a;if(1===d.length)d.pop();else{var c=d.indexOf(b);-1!==c&&(d[c]=d.pop())}}function C(a){a=a.b;if(0===(a.a&E)){a.a|=E;F(a);var b=p();y(b,a,a.i)}}
function G(a,b,d){this.f=a;this.i=b;this.b=d;this.h=this.a=this.c=this.g=this.j=null}function J(a,b){a.j=b;return a}function K(a,b){a.c=b;return a}function L(a,b){return a.f===b.f&&a.i===b.i&&a.j===b.j&&!0}function M(a,b){var d=a.f;0!==(d&1)?a.a=document.createTextNode(a.b):0!==(d&2)?a.a=0===(d&16)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):0!==(d&4)&&(d=N(a.i,a.b,b),a.a=d.g,a.h=d)}
function O(a,b){var d,c,e,f,g=a.f,h,m;if(0!==(g&14)){h=a.a;if(null!==a.g)for(m=h.style,f=Object.keys(a.g),d=0,c=f.length;d<c;d++)e=f[d],m.setProperty(e,a.g[e],"");d=null;null!==a.j&&(d=a.j);null!==d&&(0!==(g&2)?(a.b=d,h.className=d):0!==(g&4)?h.className=d:(c=h.className,h.className=""===c?d:c+" "+d));if(0!==(g&4))P(a.h);else if(null!==a.c)if(g=a.c,"string"===typeof g)h.textContent=g;else for(d=0,c=a.c.length;d<c;d++)Q(a,a.c[d],null,b)}}
function R(a,b,d){var c=a.f,e=a.c;a.a=b;if(0!==(c&4))e=a.i,b=new S(11,e,d,a.b,0,b),null!==e.a&&e.a(b),P(a.h=b);else if(null!==e&&"string"!==typeof e&&0<e.length){for(var c=b.firstChild,f;8===c.nodeType;)f=c,c=c.nextSibling,b.removeChild(f);for(a=0;a<e.length;a++)for(R(e[a],c,d),c=c.nextSibling;8===c.nodeType;)f=c,c=c.nextSibling,b.removeChild(f)}}
function T(a,b,d){var c=a.a,e=a.f;b.a=c;if(0!==(e&1))a.b!==b.b&&(a.a.nodeValue=b.b);else if(0!==(e&14)){if(a.g!==b.g){var f=a.g,g=b.g,c=c.style,h,m,l,k;if(null!==f)if(null===g)for(k=Object.keys(f),h=0,m=k.length;h<m;h++)c.removeProperty(k[h]);else{k=Object.keys(f);h=0;for(m=k.length;h<m;h++)l=k[h],g.hasOwnProperty(l)?c.setProperty(l,g[l],""):c.removeProperty(l);k=Object.keys(g);h=0;for(m=k.length;h<m;h++)l=k[h],f.hasOwnProperty(l)||c.setProperty(l,g[l],"")}else if(null!==g)for(k=Object.keys(g),h=
0,m=k.length;h<m;h++)l=k[h],c.setProperty(l,g[l],"")}0!==(e&2)&&(b.b=a.b);if(0!==(e&4))d=b.h=a.h,a.b!==b.b&&(d.f=b.b,d.a|=E),P(d);else if(e=a.c,b=b.c,c=0,h=!1,"string"===typeof e)if("string"===typeof b)e!==b&&((d=a.a.firstChild)?d.nodeValue=b:a.a.textContent=b);else{if(null!==b)for(;c<b.length;)Q(a,b[c++],null,d)}else if("string"===typeof b){if(null!==e)for(;c<e.length;)U(a,e[c++]);a.a.textContent=b}else if(null!==e&&0!==e.length)if(null===b||0===b.length)for(;c<e.length;)U(a,e[c++]);else if(1===
e.length&&1===b.length)f=e[0],g=b[0],L(f,g)?T(f,g,d):(b=g,e=f,M(b,d),a.a.replaceChild(b.a,e.a),O(b,d));else if(1===e.length){f=e[0];if(0===(a.f&32))for(;c<b.length;){g=b[c++];if(L(f,g)){T(f,g,d);h=!0;break}Q(a,g,f.a,d)}else for(;c<b.length;){g=b[c++];T(f,g,d);h=!0;break}if(h)for(;c<b.length;)Q(a,b[c++],null,d);else U(a,f)}else if(1===b.length){g=b[0];if(0===(a.f&32))for(;c<e.length;){f=e[c++];if(L(f,g)){T(f,g,d);h=!0;break}U(a,f)}else for(;c<e.length;){f=e[c++];T(f,g,d);h=!0;break}if(h)for(;c<e.length;)U(a,
e[c++]);else Q(a,g,null,d)}else if(0===(a.f&32)){f=c=0;h=e.length-1;for(g=b.length-1;c<=h&&f<=g;){k=e[c];l=b[f];if(!L(k,l))break;c++;f++;T(k,l,d)}for(;c<=h&&f<=g;){k=e[h];l=b[g];if(!L(k,l))break;h--;g--;T(k,l,d)}for(;c<=h&&f<=g;)if(k=e[c++],l=b[f++],L(k,l))T(k,l,d);else{m=a;var n=d;M(l,n);m.a.replaceChild(l.a,k.a);O(l,n)}if(c<=h){do U(a,e[c++]);while(c<h)}else if(f<=g){e=g+1;e=e<b.length?b[e].a:null;do Q(a,b[f++],e,d);while(f<g)}}else{f=l=0;k=e.length-1;m=b.length-1;var g=e[l],c=b[f],v,D,n=0;a:do for(;;){T(g,
c,d);l++;f++;if(l>k||f>m)break a;g=e[l];c=b[f]}while(l<=k&&f<=m);if(l>k)for(k=m+1,k=k<b.length?b[k].a:null;f<=m;)Q(a,b[f++],k,d);else if(f>m)for(;l<=k;)U(a,e[l++]);else{var w=k-l+1,c=m-f+1,g=Array(c);for(h=0;h<c;h++)g[h]=-1;var H=!1,I=0;if(16>=w*c)for(h=l;h<=k;h++){var x=!0;v=e[h];for(l=f;l<=m;){D=b[l];g[l-f]=h;n>l?H=!0:n=l;T(v,D,d);x=!1;break}x&&(U(a,v),I++)}else{x={};for(h=f;h<=m;h++)x[null]=h;for(h=l;h<=k;h++)v=e[h],l=x[null],void 0!==l?(D=b[l],g[l-f]=h,n>l?H=!0:n=l,T(v,D,d)):(U(a,v),I++)}if(H){h=
g.slice(0);e=[];e.push(0);m=0;for(l=g.length;m<l;m++)if(-1!==g[m])if(k=e[e.length-1],g[k]<g[m])h[m]=k,e.push(m);else{k=0;for(n=e.length-1;k<n;)w=(k+n)/2|0,g[e[w]]<g[m]?k=w+1:n=w;g[m]<g[e[k]]&&(0<k&&(h[m]=e[k-1]),e[k]=m)}k=e.length;for(n=e[k-1];0<k--;)e[k]=n,n=h[n];l=e.length-1;for(h=c-1;0<=h;h--)-1===g[h]?(m=h+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,Q(a,c,k,d)):0>l||h!==e[l]?(m=h+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,a.a.insertBefore(c.a,k)):l--}else if(w-I!==c)for(h=c-1;0<=h;h--)-1===g[h]&&(m=
h+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,Q(a,c,k,d))}}else if(null!==b&&0<b.length)for(c=0;c<b.length;c++)Q(a,b[c],null,d)}}function V(a){if(0!==(a.f&4)){a=a.h;a.a&=-3;var b=a.c;if(null!==b)for(var d=0;d<b.length;d++){var c=b[d];B(c.a,c)}a.c=null;F(a);null!==a.b&&V(a.b)}else if(null!==a.c&&(a=a.c,"string"!==typeof a))for(b=0;b<a.length;b++)V(a[b])}function Q(a,b,d,c){M(b,c);a.a.insertBefore(b.a,d);O(b,c)}function U(a,b){a.a.removeChild(b.a);V(b)}function W(){this.b=this.a=null}var E=1;
function S(a,b,d,c,e,f){this.a=a;this.j=b;this.i=null===d?0:d.i+1;this.f=c;this.g=f;this.h=this.c=this.b=null}function P(a){3===(a.a&3)&&(a.j.b(a),a.a&=~E)}function X(a,b){null===a.b?(b.h=a,0!==(a.a&8)?(R(b,a.g,a),a.a&=-9):(b.a=a.g,O(b,a))):T(a.b,b,a);a.b=b}function F(a){var b=a.h;if(null!==b)for(var d=0;d<b.length;d++){var c=b[d];B(c.a,c)}a.h=null}function N(a,b,d){b=new S(3,a,d,b,0,document.createElement("div"));null!==a.a&&a.a(b);return b};function aa(){this.a=0;this.b=new z}function ba(){function a(){for(var c=0;10>c;c++){var d=b[c];d.a++;var d=d.b,f=q.b;if(d.c<f){d.c=f;var f=d.a,g=void 0;if(null!==f)for(g=0;g<f.length;g++)C(f[g]);f=d.b;if(null!==f)for(d.b=null,g=0;g<f.length;g++)C(f[g])}}setTimeout(a,0)}for(var b=this.a=[],d=0;100>d;d++)b.push(new aa);setTimeout(a,0)}var Y=new W;Y.a=function(a){var b=a.f.b,d=new A(b,a),c;c=b.a;null===c&&(b.a=c=[]);c.push(d);b=a.c;null===b&&(a.c=b=[]);b.push(d)};
Y.b=function(a){var b=a.f.a,d=10*Math.sin(b/10),c=10*Math.cos(b/10),e=b%255,b=b%100,f=J(new G(8,null,null),"b"),g=J(new G(2,"div",null),"c");g.g={top:d+"px",left:c+"px",background:"rgb(0,0,"+e+")"};X(a,K(f,[K(g,b.toString())]))};var Z=new W;Z.b=function(a){for(var b=a.f.a,d=Array(b.length),c=0;c<b.length;c++){var e=b[c],f=Y;void 0===e&&(e=null);d[c]=new G(4,f,e)}X(a,K(J(new G(8,null,null),"a"),d))};
q=new function(){this.a=0;this.b=1;this.c=[];this.h=[];this.g=new u;this.f=new u;var a=this;new r(function(){a.a|=256;for(var b=a.c;0<b.length;){a.c=[];for(var d=0;d<b.length;d++)b[d]();b=a.c}a.b++;a.a&=-258});new t(function(){a.a&=-3;a.a|=256;var b=a.h;if(0<b.length){a.h=[];for(var d=0;d<b.length;d++)b[d]()}a.b++;a.a&=-257});this.i=function(){var b,d,c,e,f,g;a.a&=-9;a.a|=256;b=a.f;a.f=a.g;a.g=b;do{for(;0!==(b.a&3);){if(0!==(b.a&1))for(b.a&=-2,d=b.b,f=0;f<d.length;f++)if(c=d[f],null!==c)for(d[f]=
null,g=0;g<c.length;g++)e=c[g],e.constructor===S?P(e):e.call();if(0!==(b.a&2))for(b.a&=-3,c=b.c,f=0;f<c.length;f++)e=c[f],e.constructor===S?P(e):e.call()}for(;0!==(b.a&4);)for(b.a&=-5,c=b.f,b.f=null,f=0;f<c.length;f++)e=c[f],e()}while(0!==(b.a&3));for(;0!==(b.a&8);)for(b.a&=-9,c=b.g,f=0;f<c.length;f++)e=c[f],e();a.b++;a.a&=-257}};document.addEventListener("DOMContentLoaded",function(){var a=new ba;y(p(),function(){var b=document.body,d=N(Z,a,null);b.appendChild(d.g);P(d)})});}).call();
